### ISSUE TITLE
bot-conversation-sso-quickstart csharp version has build errors

### ISSUE THREAD

**Issue by appieschot** [OfficeDev/Microsoft-Teams-Samples#1326]
When pulling in the csharp version of the **bot-conversation-sso-quickstart** available at: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore/BotConversationSsoQuickstart

The F5 experience does not work due to conflicting changes. 

The build experience uses the file `BotConversationSsoQuickstart\teamsapp.local.yml` to run. That file contains `teamsApp/validateManifest` that refers to the following: 

```
  - uses: teamsApp/validateManifest
    with:
      # Path to manifest template
      manifestPath: ./AppManifest/manifest.json
```

That file path does not exist, it most likely must point to `../TeamsApp/appPackage/manifest.json` 

The same is for all following steps:
- zipAppPackage
- validateAppPackage
- update 

Happy to create a pull request with changes if we agree on that approach.
