### ISSUE TITLE
Error: botAadApp/create failed due to service management reference

### ISSUE THREAD

**Issue by yuting1008** [OfficeDev/Microsoft-Teams-Samples#1441]
I am reproducing https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/msgext-expert-finder-js.
When setting up resources, I fail to run the app in a Teams web client.

>   (×) Error: botAadApp/create failed.
    (×) Error: Service management reference is required when creating Microsoft Entra app in Microsoft tenant. Please refer to the help link to provide a valid service management reference.
  (!) Warning: botFramework/create was not executed.
  (!) Warning: teamsApp/validateManifest was not executed.
  (!) Warning: teamsApp/zipAppPackage was not executed.
  (!) Warning: teamsApp/validateAppPackage was not executed.
  (!) Warning: teamsApp/update was not executed.
  (!) Warning: teamsApp/extendToM365 was not executed.

Below is the botAadApp/create.

```
  # Create or reuse an existing Azure Active Directory application for bot.
  - uses: botAadApp/create
    with:
      # The Azure Active Directory application's display name
      name: expert-finder-${{TEAMSFX_ENV}}
    writeToEnvironmentFile:
      # The Azure Active Directory application's client id created for bot.
      botId: BOT_ID
      # The Azure Active Directory application's client secret created for bot.
      botPassword: SECRET_BOT_PASSWORD
```

How to fix this issue? Thank you!
